### ISSUE TITLE
JavaScript hooks

### ISSUE THREAD

**Issue by remoteboy** [codemanas/cm-typesense-docs#10]
Are there any events triggered in JavaScript that I can hook into? I have two things I'd like to achieve

1. analytics integration - everytime a user searches for a term, or clicks on a link I'd like to send some data to our GA property
2. alternate trigger for launching the Instant Search box. Currently I'm using the 'Replace WordPress Search' option but ideally i'd like to just have a search icon that i can click on to launch the Instant Search box.

**Comment by digamber89** [comment]
Hi @remoteboy ,

1. For analytics please use the custom event cmswt_search_state_changed as suggested it run when the search state changes
2. For alternate trigger that is already supported via [Trigger](https://docs.wptypesense.com/getting-started/#instant-search-popup) - this will trigger the popup.

**Comment by remoteboy** [comment]
Thanks - got the Trigger working but not sure how to hook into the cmswt_search_state_changed event?

**Comment by digamber89** [comment]
Please check this.
```  
document.addEventListener('cmswt_search_state_changed', function(eventState){
      if( eventState === undefined) return;
      const {detail:state} = eventState;
      console.log('State of Search',state)
  });
 ```

**Comment by remoteboy** [comment]
Thanks. I've tried that but it doesn't seem to be triggering on state change. This is the code - 

```
watchSearchPopUp();

function watchSearchPopUp(){
    console.log('watching');
    document.addEventListener('cmswt_search_state_changed', function(eventState){
        console.log('clicked');
        if( eventState === undefined) return;
        const {detail:state} = eventState;
        console.log('State of Search',state)
    });
}
```

The console logs `watching` but never logs `clicked` or `state`. 

I'm not seeing any errors in the console.

**Comment by remoteboy** [comment]
Actually it seems to echo the state of search when i change tabs or type a search term, just not for the pop up.

**Comment by remoteboy** [comment]
Thanks - that works a treat.
