### ISSUE TITLE
Search term highlighting + combining collections.

### ISSUE THREAD

**Issue by joshuaiz** [codemanas/cm-typesense-docs#12]
Hello,

1. **Search Term Highlighting**: I was able to get search results using the plugin to index Posts and Pages and then using the JavaScript client to query via the API for my headless site. Yet, the returned results do not have the search term highlighted or surrounded by `<mark></mark>` tags. According to the API docs, this should be on by default. Is there a way to get highlighting working when coming from WordPress? In the Typesense admin, when performing a search the term is highlighted there as seen here:

![CleanShot 2024-07-10 at 20 35 39@2x](https://github.com/codemanas/cm-typesense-docs/assets/1096738/31a05564-3e69-4ccb-a138-18b1a6c83dde)

Alternatively, there is also the JSON format as shown here:

![CleanShot 2024-07-10 at 20 37 49@2x](https://github.com/codemanas/cm-typesense-docs/assets/1096738/8cdc3635-cf92-4dfa-a249-f0c97f26e908)

![CleanShot 2024-07-10 at 20 36 37@2x](https://github.com/codemanas/cm-typesense-docs/assets/1096738/c0fd70da-2616-4b66-94c5-838f84bd4651)

Is there a way to get that JSON returned from search instead of the normal document? With that I could display the highlighted snippet instead of an excerpt. I guess that is more a Typesense API question but I have not found a way to do it.

2. **Combining collections**. In the Typesense docs, they recommend combining collections into one e.g. `posts | pages` and then querying against that to provide a global search. How would I go about doing that with the plugin? Is there a function to combine the different indices?

**Comment by digamber89** [comment]
Hi @joshuaiz 

Depends on what you're using to show results on the frontend.
[Instant Search](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/)
We are using instant search to render search results on the frontend.

As for combined collections - the only problem is that you need a unified schema.
This is not possible out of the box - you will have to define a custom schema and work that way.
Please have a look at this for a [starting point](https://wordpress.org/support/topic/combine-results-2/)
Github Repo: [https://github.com/codemanas/omni-search/tree/master](https://github.com/codemanas/omni-search/tree/master)

**Comment by joshuaiz** [comment]
Hi @digamber89 

1. Highlighting...I am just using a JavaScript client from Typesense:

```js
let searchParameters = {
	q: searchQuery,
	query_by: ['post_content', 'post_title'],
	include_fields: [
		'post_title',
		'post_content',
		'post_excerpt',
		'post_thumbnail',
		'permalink',
		'post_date'
	]
}

let results = await client.collections('post').documents().search(searchParameters)

const documents = results.hits.map((document) => {
	return document.document
})

// UI code below
```
Not sure why this does not return the term highlighted when it is highlighted in the Typesense portal.

And what about the JSON view that is available in Typesense...is it possible to return that?

Personally even though I've used Algolia before, I would prefer not to use their library and the connector but maybe that is the only way to get highlighting?


2. Combining collections. Got it - makes sense. I will give that a go.


Thanks!

**Comment by digamber89** [comment]
As you can see from the json they sent it's matched tokens, snippet and value.
Algolia's Instant Search uses those to render the final result.
So in your implementation - you have to do the same.
On typesnse's cluster implementation to they are doing something similar.
So it's not just about retrieving - it requires a bit of manipulation to show the data as intended too.

**Comment by joshuaiz** [comment]
@digamber89 this was developer error: (me).

I was mapping the results into a documents array and skipping over the `hits`. All of that snippet data is there in the `hits` so I am all set.

This is resolved - thanks!
