### ISSUE TITLE
Best result on search is not bringing it's group (post type) to top of result

### ISSUE THREAD

**Issue by cp-bwg** [codemanas/cm-typesense-docs#4]
Currently when I do an exact match search, the post is found but it is contained inside its custom post type grouping, and that grouping does not change rank order.  That post type is last in the "Post Types to Enable" list. Don't we think that the matching priority should be taken into account before the order of the Posts Types to Enable grouping?

**Comment by digamber89** [comment]
Hi @cp-bwg 

I am not sure what you mean here - can you please provide more details.
