### ISSUE TITLE
No custom post types appearing in Instant Search

### ISSUE THREAD

**Issue by remoteboy** [codemanas/cm-typesense-docs#7]
Not sure if I've misconfigured something, but I've added a few additional post types - Podcasts, Videos. When I replace the WordPress search with Autocomplete, I can see that they are included in the search results, but when I replace the WordPress search with Instant Search, it only searches Posts.

**Comment by digamber89** [comment]
Hi @remoteboy 

Have you specified the post types in the shortcode ? If the post types to be included in the instant search are not specified they won't show up.
